//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMaragementClient.LoanDetailServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanDetailServiceReference.ILoanDetailService")]
    public interface ILoanDetailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/Add", ReplyAction="http://tempuri.org/ILoanDetailService/AddResponse")]
        int Add(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/Add", ReplyAction="http://tempuri.org/ILoanDetailService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/Delete", ReplyAction="http://tempuri.org/ILoanDetailService/DeleteResponse")]
        int Delete(int loanDetailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/Delete", ReplyAction="http://tempuri.org/ILoanDetailService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int loanDetailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/GetAll", ReplyAction="http://tempuri.org/ILoanDetailService/GetAllResponse")]
        System.Data.DataTable GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/GetAll", ReplyAction="http://tempuri.org/ILoanDetailService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/Update", ReplyAction="http://tempuri.org/ILoanDetailService/UpdateResponse")]
        int Update(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/Update", ReplyAction="http://tempuri.org/ILoanDetailService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/GetLoanDetailsByLoanId", ReplyAction="http://tempuri.org/ILoanDetailService/GetLoanDetailsByLoanIdResponse")]
        DatabaseAccess.DataTransferObjects.LoanDetail[] GetLoanDetailsByLoanId(int loanId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/GetLoanDetailsByLoanId", ReplyAction="http://tempuri.org/ILoanDetailService/GetLoanDetailsByLoanIdResponse")]
        System.Threading.Tasks.Task<DatabaseAccess.DataTransferObjects.LoanDetail[]> GetLoanDetailsByLoanIdAsync(int loanId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/GetLoanDetails", ReplyAction="http://tempuri.org/ILoanDetailService/GetLoanDetailsResponse")]
        DatabaseAccess.DataTransferObjects.LoanDetail[] GetLoanDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanDetailService/GetLoanDetails", ReplyAction="http://tempuri.org/ILoanDetailService/GetLoanDetailsResponse")]
        System.Threading.Tasks.Task<DatabaseAccess.DataTransferObjects.LoanDetail[]> GetLoanDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoanDetailServiceChannel : LibraryMaragementClient.LoanDetailServiceReference.ILoanDetailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanDetailServiceClient : System.ServiceModel.ClientBase<LibraryMaragementClient.LoanDetailServiceReference.ILoanDetailService>, LibraryMaragementClient.LoanDetailServiceReference.ILoanDetailService {
        
        public LoanDetailServiceClient() {
        }
        
        public LoanDetailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanDetailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanDetailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanDetailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail) {
            return base.Channel.Add(loanDetail);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail) {
            return base.Channel.AddAsync(loanDetail);
        }
        
        public int Delete(int loanDetailId) {
            return base.Channel.Delete(loanDetailId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int loanDetailId) {
            return base.Channel.DeleteAsync(loanDetailId);
        }
        
        public System.Data.DataTable GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public int Update(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail) {
            return base.Channel.Update(loanDetail);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(DatabaseAccess.DataTransferObjects.LoanDetail loanDetail) {
            return base.Channel.UpdateAsync(loanDetail);
        }
        
        public DatabaseAccess.DataTransferObjects.LoanDetail[] GetLoanDetailsByLoanId(int loanId) {
            return base.Channel.GetLoanDetailsByLoanId(loanId);
        }
        
        public System.Threading.Tasks.Task<DatabaseAccess.DataTransferObjects.LoanDetail[]> GetLoanDetailsByLoanIdAsync(int loanId) {
            return base.Channel.GetLoanDetailsByLoanIdAsync(loanId);
        }
        
        public DatabaseAccess.DataTransferObjects.LoanDetail[] GetLoanDetails() {
            return base.Channel.GetLoanDetails();
        }
        
        public System.Threading.Tasks.Task<DatabaseAccess.DataTransferObjects.LoanDetail[]> GetLoanDetailsAsync() {
            return base.Channel.GetLoanDetailsAsync();
        }
    }
}
