//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMaragementClient.AuthorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorServiceReference.IAuthorService")]
    public interface IAuthorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/Add", ReplyAction="http://tempuri.org/IAuthorService/AddResponse")]
        int Add(DatabaseAccess.DataTransferObjects.Author author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/Add", ReplyAction="http://tempuri.org/IAuthorService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(DatabaseAccess.DataTransferObjects.Author author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/Delete", ReplyAction="http://tempuri.org/IAuthorService/DeleteResponse")]
        int Delete(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/Delete", ReplyAction="http://tempuri.org/IAuthorService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAll", ReplyAction="http://tempuri.org/IAuthorService/GetAllResponse")]
        System.Data.DataTable GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAll", ReplyAction="http://tempuri.org/IAuthorService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/Update", ReplyAction="http://tempuri.org/IAuthorService/UpdateResponse")]
        int Update(DatabaseAccess.DataTransferObjects.Author author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/Update", ReplyAction="http://tempuri.org/IAuthorService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(DatabaseAccess.DataTransferObjects.Author author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAuthors", ReplyAction="http://tempuri.org/IAuthorService/GetAuthorsResponse")]
        System.Collections.Generic.List<DatabaseAccess.DataTransferObjects.Author> GetAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorService/GetAuthors", ReplyAction="http://tempuri.org/IAuthorService/GetAuthorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatabaseAccess.DataTransferObjects.Author>> GetAuthorsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorServiceChannel : LibraryMaragementClient.AuthorServiceReference.IAuthorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorServiceClient : System.ServiceModel.ClientBase<LibraryMaragementClient.AuthorServiceReference.IAuthorService>, LibraryMaragementClient.AuthorServiceReference.IAuthorService {
        
        public AuthorServiceClient() {
        }
        
        public AuthorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(DatabaseAccess.DataTransferObjects.Author author) {
            return base.Channel.Add(author);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(DatabaseAccess.DataTransferObjects.Author author) {
            return base.Channel.AddAsync(author);
        }
        
        public int Delete(int authorId) {
            return base.Channel.Delete(authorId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int authorId) {
            return base.Channel.DeleteAsync(authorId);
        }
        
        public System.Data.DataTable GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public int Update(DatabaseAccess.DataTransferObjects.Author author) {
            return base.Channel.Update(author);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(DatabaseAccess.DataTransferObjects.Author author) {
            return base.Channel.UpdateAsync(author);
        }
        
        public System.Collections.Generic.List<DatabaseAccess.DataTransferObjects.Author> GetAuthors() {
            return base.Channel.GetAuthors();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatabaseAccess.DataTransferObjects.Author>> GetAuthorsAsync() {
            return base.Channel.GetAuthorsAsync();
        }
    }
}
